/**
 * This class implements Multiplier and Divider and initializes their methods. Also, this class declares
 * the calculate method.
 *
 * JDK version: 11.0.3
 *
 * @author  Kyrel Polifrone || 822711442 || CS108 Section 04
 * @version 1.0.0
 * @since   04-18-2020
 */


public abstract class Calculator implements Multiplier, Divider {
    protected int total;

    /**
     * Default constructor for calculator
     */
    public Calculator() {
        total = 1;
    }

    /**
     * This method takes the inputted value and multiples the total by this value
     * @param y - integer which will be total will be multiplied by
     */
    @Override
    public void multiply(int y) {
        total *= y;
    }

    /**
     * This method takes the input value and divides it from the total value
     * @param y - integer which total will be divided by
     */
    @Override
    public void divide(int y) {
        total /= y;
    }

    /**
     * Declaration of the abstract calculate method.
     * @return - returns an int value generated by the calculate method
     */
    public abstract int calculate();
}
